# Use the official PostgreSQL image from the Docker Hub
FROM postgres:latest

# Set environment variables for PostgreSQL
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=adminpassword
ENV POSTGRES_DB=battleship


# Expose the default PostgreSQL port
EXPOSE 5432


# The default command to run PostgreSQL
CMD ["postgres"]